apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: my-deploy
  name: my-deploy-2
  namespace: dev
spec:
  replicas: 2
  selector:
    matchLabels:
      app: my-deploy-2
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: my-deploy-2
    spec:
      containers:
      - image: nginx:alpine
        name: nginx
        resources: {}
status: {}
